version: '3.8'

services:
  web:
    build: .
    container_name: kgvisualizer_dashboard
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
    restart: always
